### ISSUE TITLE
results not displaying 

### ISSUE THREAD

**Issue by johnkorzhuk** [eusi/alfred2-twitch-streamer#6] opened 2016-10-02 15:01 UTC
Here's a gyazo of my issue: https://gyazo.com/23223c3fd3e8af6b2c3909db6db28013
https://gyazo.com/9c182876b0f7b7a56a1ed164595965a1

Whenever I enter a query, the workflow is being ignored. Any idea why this is happening?

Also worth noting I'm on macOS Sierra 10.12 and using Alfred 3.1.1

**Comment by eusi** [comment] 2016-10-02 17:18
You are using the latest 1.73 of TwitchStreamer?

**Comment by johnkorzhuk** [comment] 2016-10-02 17:19
Yes I am

**Comment by johnkorzhuk** [comment] 2016-10-02 17:21
I was able to get livestreamer to work on its own with the oauth workaround

**Comment by eusi** [comment] 2016-10-02 17:57
Currently I cannot reproduce the issue.
I will upgrade to macOS Sierra now. Let's see this occurs the problem.

**Comment by eusi** [comment] 2016-10-02 19:11
Ok, I got also the issue with macOS Sierra. I gonna fix it now and release 1.74 afterwards. Thanks for reporting!

**Comment by johnkorzhuk** [comment] 2016-10-02 19:11
Alright sweet! Thanks for getting back with me so quick.

**Comment by eusi** [comment] 2016-10-02 21:32
Should be fixed now. Please check it out :-)

**Closed by eusi** 2016-10-02 21:32 UTC

**Comment by johnkorzhuk** [comment] 2016-10-03 14:11
It works. Thanks again.
